apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-graphql-api
  labels:
    app: hr-graphql-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-graphql-api
  template:
    metadata:
      labels:
        app: hr-graphql-api
    spec:
      containers:
      - name: hr-graphql-api
        image: us-east1-docker.pkg.dev/newwwbi-playground/newwwbi-registry/hr-graphql-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: APP_NAME
          value: "hr-graphql-api"
        - name: APP_ENV
          value: "prod"
        - name: PORT
          value: "3000"
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_NODE_ENABLED_INSTRUMENTATIONS
          value: "nestjs-core,graphql"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hr-graphql-api-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"